### ISSUE TITLE
Version 1.0 roadmap

### ISSUE THREAD

**Issue by timonf** [timonf/twigony-bundle#1]
Roadmap for version 1.0:

- [x] [TemplateController]    Ability to display a single page
- [x] [TemplateController]    Ability to display multiple pages with one route
- [x] [DoctrineORMController] List entities
- [x] [DoctrineORMController] List entities / pagination
- [x] [DoctrineORMController] View single entity
- [x] [DoctrineORMController] Create single entity
- [x] [DoctrineORMController] Edit single entity
- [x] ~~[DoctrineORMController] Delete single entity~~
- [x] [SwiftMailerController] Send email through a form
- [x] [SecurityController]    Login form (default from Symfony documentation)
- [x] [AutomaticFormBuilder]  (Only for prototyping!) Creating Form from Entity
- [x] [Controller]            Implement cache parameters (max-age, smax-age, public/private)
- [x] [Controller]            Implement some security (role/user checking ~~, maybe voter support~~)
- [x] [Documentation]         Readme: Installation description
- [x] [Documentation]         Readme: Some usage examples
- [x] [Documentation]         Create structure for detailed documentation
- [x] [Documentation]         Create separate detailed documentation for TemplateController
- [x] [Documentation]         Create separate detailed documentation for DoctrineORMController
- [x] [Documentation]         Create separate detailed documentation for SwiftMailerController
- [x] [Documentation]         Create separate detailed documentation for SecurityController
- [x] [Testing]               Some unit tests
- [ ] [Testing]               >= 80% coverage
- [ ]                         Create public example project
- [x]                         Check Doc Blocks
- [x]                         Check CHANGELOG
- [ ]                         Symfony Flex Recipe
